networks:
    webdav_network:
        driver: bridge
    ipvlan:
        external: true
        name: ipvlan_network
services:
    webdav:
        image: dgraziotin/nginx-webdav-nononsense
        volumes:
            - /home/$USER:/data
        environment:
            PUID: $ADMIN_PUID
            PGID: $ADMIN_PGID
            WEBDAV_USERNAME: $ADMIN_WEBDAV_USERNAME
            WEBDAV_PASSWORD: $ADMIN_WEBDAV_PASSWORD
            SERVER_NAMES: localhost
            TIMEOUTS_S: 1200
            CLIENT_MAX_BODY_SIZE: 1G
        networks:
            - webdav_network
        restart: unless-stopped
    servers:
        image: dqio/servers:latest
        environment:
            SERVER_YAML: /etc/nginx/yaml/servers.yaml
            SERVER_WATCH_CRT: /var/local/step/site.crt
        volumes:
            - ~/Docker/Services/step/tmp:/var/local/step:ro
            - ./servers.yaml:/etc/nginx/yaml/servers.yaml
        networks:
            webdav_network:
            ipvlan:
                ipv4_address: $SERVER_IPVLAN_ADDRESS
        ports:
            - 80
            - 443
        depends_on:
            - webdav
        restart: unless-stopped

