networks:
    webdav_network:
        driver: bridge
    ipvlan:
        external: true
        name: ipvlan_network
    ca:
        external: true
        name: step_ca_network
volumes:
    step:
        driver: local
secrets:
    provisioner_password:
        file: $PROVISIONER_PASSWORD_FILE
services:
    crt:
        image: dqio/crtpatch:latest
        environment:
            STEP_INIT_NAME: $CRT_STEP_INIT_NAME
            STEP_INIT_DNS: $CRT_STEP_INIT_DNS
            STEP_CA_URL: $CRT_STEP_CA_URL
            STEP_FINGERPRINT: $CRT_STEP_FINGERPRINT
            STEP_KID: $CRT_STEP_KID
            STEP_RENEW_PERIOD: $CRT_STEP_RENEW_PERIOD
            STEP_PROVISIONER_PASSWORD_FILE: /run/secrets/provisioner_password
        volumes:
            - step:/var/local/step
        secrets:
            - provisioner_password
        networks:
            - ca
        restart: unless-stopped
    webdav:
        image: dgraziotin/nginx-webdav-nononsense
        volumes:
            - /home/$USER:/data
        environment:
            PUID: $ADMIN_PUID
            PGID: $ADMIN_PGID
            WEBDAV_USERNAME: $ADMIN_WEBDAV_USERNAME
            WEBDAV_PASSWORD: $ADMIN_WEBDAV_PASSWORD
            SERVER_NAMES: localhost
            TIMEOUTS_S: 1200
            CLIENT_MAX_BODY_SIZE: 1G
        networks:
            - webdav_network
        restart: unless-stopped
    servers:
        image: dqio/servers:latest
        environment:
            SERVER_YAML: /etc/nginx/yaml/servers.yaml
            SERVER_WATCH_CRT: /var/local/step/site.crt
        volumes:
            - step:/var/local/step:ro
            - ./servers.yaml:/etc/nginx/yaml/servers.yaml
        networks:
            webdav_network:
            ipvlan:
                ipv4_address: $SERVER_IPVLAN_ADDRESS
        ports:
            - 80
            - 443
        depends_on:
            - webdav
        restart: unless-stopped

